### ISSUE TITLE
make-secrets-writable init container uses latest image

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/helm-charts-interactive-services#144]
Hi !  

It seems the `make-secrets-writable` init container uses `latest` as tag for `inseefrlab/onyxia-base`. 
This results in Kubernetes applying `Always` as `ImagePullPolicy` which can be an unwanted behaviour for some organizations. 
Could we switch to using proper tags ? Or would it have unwanted consequences (like having to change every chart each time the `onyxia-base` image changes) ?

**Comment by fcomte** [comment]
what about enforce ifNotPresent in our charts?

**Comment by avouacr** [comment]
fixed in #27dbdb9 (introducing versioning of onyxia-base would introduce too much uneeded complexity)
