### ISSUE TITLE
Add multiple port for expose services

### ISSUE THREAD

**Issue by titigmr** [InseeFrLab/helm-charts-interactive-services#173]
Hello, it's possible to expose multiple port when we launch a service? 

It could be great instead of choosing one port:
![image](https://github.com/user-attachments/assets/943e368a-fdce-4d7d-be92-a3c5b421c7a9)

Add multiple ports with a list, like extraEnvVars section:
![image](https://github.com/user-attachments/assets/0f53969d-f250-4fdb-8651-5711c525c1e7)

And for exemple each ingresses are accessibles with: 
`https://<user-release>-<port-number>.user.lab.sspcloud.fr/`

**Comment by Gaspi** [comment]
Hello @titigmr, thanks a lot for the excellent suggestion.
As you can see, I have started working on implementing this and it should be available shortly.

The legacy value `networking.user.port` will continue to be usable but it is now overridden by the array `networking.user.ports` when provided.

**Comment by titigmr** [comment]
Nice! Do you want help for this feature?

**Comment by Gaspi** [comment]
I should be fine but I will make sure to properly tag all commits related to this issue. Any feedback or recommandation are most welcome.
