### ISSUE TITLE
rstudio does not clone project

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/helm-charts-interactive-services#54]
User can't clone directly on the launcher : 

This line is broken : 

https://github.com/InseeFrLab/helm-charts-interactive-services/blob/c3067d02d41488a8879c6efa8c0652a067590e41/charts/rstudio/templates/statefulset.yaml#L79

We should remove the condition `{{- if .Values.environment.root }}` and I think`ROOT=TRUE` is no more used

**Comment by avouacr** [comment]
Fixed in 70ff601b714a9a91e32ae77bb428cae3bbd0aeab
