### ISSUE TITLE
Not able to modify/configure hive-site.xml file in /hive/conf/hive-site.xml

### ISSUE THREAD

**Issue by nashugame** [InseeFrLab/helm-charts-interactive-services#74]
Hi,
Not able to modify hive-site.xml file even with root privileges.
![Screenshot from 2023-06-01 14-26-39](https://github.com/InseeFrLab/helm-charts-interactive-services/assets/34041404/faf9e8f4-105f-443d-96e2-156e52670a23)

**Comment by avouacr** [comment]
Hi @nashugame, #9bf013907812a39576709f0a28b8b857f6ddc981 should have fixed this. Could you try it again?
