### ISSUE TITLE
Automatically use dark mode if Onyxia is in dark mode also

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/helm-charts-interactive-services#92]
This feature concern a mix of work in : 

- [x] Onyxia-web : https://github.com/InseeFrLab/onyxia-web/issues/581
- [x] helm charts for interactive services : https://github.com/InseeFrLab/helm-charts-interactive-services
- [x] datascience docker images : https://github.com/InseeFrLab/images-datascience/issues/137

For this repo we should try to : 

- [x] a new boolean value with a x-onyxia injection base on work in Onyxia-web
- [x] inject the choosen env variable if this boolean is true.

**Comment by avouacr** [comment]
closed by #99
