### ISSUE TITLE
Make config files writable

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/helm-charts-interactive-services#93]
In the datascience stack many config files come from configmap. This made all those file read-only. It can be quite frustrating for our users
We should generalize the use of an init container that will copy those config map file into an empty dir volume.

An example is done there : https://github.com/InseeFrLab/helm-charts-interactive-services/blob/1b36ddf6dfa689ded4f3a4a7bb89c7f70d79ea1c/charts/jupyter-pyspark/templates/statefulset.yaml#L76

**Comment by avouacr** [comment]
Done by @ihiverlet
